/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class JsPrototype {
  constructor()
  displayImage(well: number, image: Buffer): void
  setSwitchCallback(well: number, switch: string, callback: (...args: any[]) => any): void
}
