/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class JsPrototype {
  constructor()
  displayImage(well: number, image: Buffer): void
  setSwitchCallback(well: number, switch: string, callback: (...args: any[]) => any): void
  readMemory(well: number, bytes: number): Buffer
  writeMemory(well: number, data: Buffer): void
}
export class JsDevkit {
  constructor()
  displayImage(well: number, image: Buffer): void
  setSwitchCallback(well: number, switch: string, callback: (...args: any[]) => any): void
  readMemory(well: number, bytes: number): Array<number>
  writeMemory(well: number, data: Buffer): void
}
