/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export class JsPrototype {
  constructor()
  displayImage(well: number, image: Buffer): void
}
